/**
 * Database schema.
 *
 * Sign-in (Better Auth, see dashboard/src/lib/auth/): `user`, `session`, `account`
 * and `verification`, with the column set Better Auth expects.
 *
 * Learner progress mirrors .progress/progress.json (see
 * .progress/progress.example.json): one `learner` row per user, one
 * `lesson_progress` row per lesson they started, and an append-only
 * `progress_event` log of every change.
 *
 * After changing this file, run `npm run generate -w @lessonfolk/db` and commit
 * the new SQL migration in drizzle/.
 */
import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  check,
  index,
  jsonb,
  pgTable,
  primaryKey,
  real,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';

/** Lesson statuses, as in progress.json. */
export const LESSON_STATUSES = ['in_progress', 'done', 'skipped'] as const;
export type LessonStatus = (typeof LESSON_STATUSES)[number];

/** The learner profile, stored as-is (name, experience, goal, language, level, interests…). */
export type LearnerProfile = Record<string, unknown>;

const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
};

// --- Sign-in (Better Auth) ---------------------------------------------------
// Table and field names are Better Auth's defaults (the Drizzle keys); columns are
// snake_case like the rest of the schema. Ids are generated by Better Auth.

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  image: text('image'),
  ...timestamps,
});

export const session = pgTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    /** Random token stored (signed) in the session cookie. */
    token: text('token').notNull().unique(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    ...timestamps,
  },
  (table) => [index('session_user_id_idx').on(table.userId)],
);

/** One sign-in method (GitHub, Google…) linked to a user. */
export const account = pgTable(
  'account',
  {
    id: text('id').primaryKey(),
    /** The user's id at the provider. */
    accountId: text('account_id').notNull(),
    /** `github`, `google`… */
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }),
    scope: text('scope'),
    /** Unused: LessonFolk has no password sign-in. Kept because Better Auth expects it. */
    password: text('password'),
    ...timestamps,
  },
  (table) => [index('account_user_id_idx').on(table.userId)],
);

/** Short-lived values, e.g. the OAuth state while a sign-in is in progress. */
export const verification = pgTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    ...timestamps,
  },
  (table) => [index('verification_identifier_idx').on(table.identifier)],
);

// --- Learner progress ---------------------------------------------------------

export const learner = pgTable('learner', {
  /** The signed-in user (or the single local user in `LESSONFOLK_AUTH=none`). */
  userId: text('user_id')
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  profile: jsonb('profile').$type<LearnerProfile>().notNull().default({}),
  /** Recommended course ids, in order. */
  path: text('path').array(),
  pathReason: text('path_reason'),
  pathUpdatedAt: timestamp('path_updated_at', { withTimezone: true }),
  /** Lesson id (`<course-id>/<lesson file name>`) the learner is working on. */
  currentLessonId: text('current_lesson_id'),
  ...timestamps,
});

export const lessonProgress = pgTable(
  'lesson_progress',
  {
    userId: text('user_id')
      .notNull()
      .references(() => learner.userId, { onDelete: 'cascade' }),
    lessonId: text('lesson_id').notNull(),
    status: text('status').$type<LessonStatus>().notNull(),
    startedAt: timestamp('started_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    /** 0–1, the tutor's estimate from the checks. */
    score: real('score'),
    notes: text('notes'),
    ...timestamps,
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.lessonId] }),
    check('lesson_progress_status_check', sql`${table.status} in ('in_progress', 'done', 'skipped')`),
    check('lesson_progress_score_check', sql`${table.score} is null or (${table.score} >= 0 and ${table.score} <= 1)`),
  ],
);

/** Append-only: rows are inserted, never updated or deleted (except with their learner). */
export const progressEvent = pgTable(
  'progress_event',
  {
    id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
    userId: text('user_id')
      .notNull()
      .references(() => learner.userId, { onDelete: 'cascade' }),
    /** What happened, e.g. `lesson.started`, `lesson.completed`, `path.updated`. */
    action: text('action').notNull(),
    payload: jsonb('payload').$type<Record<string, unknown>>().notNull().default({}),
    /** Which client made the change (e.g. `claude-code`, `codex`, `dashboard`). */
    client: text('client'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index('progress_event_user_created_idx').on(table.userId, table.createdAt)],
);

export type User = typeof user.$inferSelect;
export type NewUser = typeof user.$inferInsert;
export type Learner = typeof learner.$inferSelect;
export type NewLearner = typeof learner.$inferInsert;
export type LessonProgress = typeof lessonProgress.$inferSelect;
export type NewLessonProgress = typeof lessonProgress.$inferInsert;
export type ProgressEvent = typeof progressEvent.$inferSelect;
export type NewProgressEvent = typeof progressEvent.$inferInsert;
