/**
 * Database schema.
 *
 * Sign-in (Better Auth, see dashboard/src/lib/auth/): `user`, `session`, `account`
 * and `verification`, with the column set Better Auth expects.
 *
 * MCP authorization server (oauth mode): `jwks` and the `oauth_*` tables.
 *
 * Learner progress mirrors a progress.json v1 file (see
 * docs/progress.example.json): one `learner` row per user, one
 * `lesson_progress` row per lesson they started, and an append-only
 * `progress_event` log of every change.
 *
 * After changing this file, run `npm run generate -w @lessonfolk/db` and commit
 * the new SQL migration in drizzle/.
 */
import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  real,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

/** Lesson statuses, as in progress.json. */
export const LESSON_STATUSES = ['in_progress', 'done', 'skipped'] as const;
export type LessonStatus = (typeof LESSON_STATUSES)[number];

/** The learner profile, stored as-is (name, experience, goal, language, level, interests…). */
export type LearnerProfile = Record<string, unknown>;

const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
};

// --- Sign-in (Better Auth) ---------------------------------------------------
// Table and field names are Better Auth's defaults (the Drizzle keys); columns are
// snake_case like the rest of the schema. Ids are generated by Better Auth.

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  image: text('image'),
  ...timestamps,
});

export const session = pgTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    /** Random token stored (signed) in the session cookie. */
    token: text('token').notNull().unique(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    ...timestamps,
  },
  (table) => [index('session_user_id_idx').on(table.userId)],
);

/** One sign-in method (GitHub, Google…) linked to a user. */
export const account = pgTable(
  'account',
  {
    id: text('id').primaryKey(),
    /** The user's id at the provider. */
    accountId: text('account_id').notNull(),
    /** `github`, `google`… */
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }),
    scope: text('scope'),
    /** Unused: LessonFolk has no password sign-in. Kept because Better Auth expects it. */
    password: text('password'),
    ...timestamps,
  },
  (table) => [index('account_user_id_idx').on(table.userId)],
);

/** Short-lived values, e.g. the OAuth state while a sign-in is in progress. */
export const verification = pgTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    ...timestamps,
  },
  (table) => [index('verification_identifier_idx').on(table.identifier)],
);

// --- MCP authorization server (Better Auth `jwt()` + `@better-auth/mcp`) ------
// With LESSONFOLK_AUTH=oauth, the app is the OAuth 2.1 authorization server of its own
// MCP endpoint (packages/mcp). Fields are those the plugins declare (Drizzle keys = Better
// Auth model and field names); tables and columns are snake_case. Unused options still
// get their column, because Better Auth writes every field it knows.

const textArray = (name: string) => text(name).array();

/** Signing keys of the access tokens (served at /api/auth/jwks). */
export const jwks = pgTable('jwks', {
  id: text('id').primaryKey(),
  publicKey: text('public_key').notNull(),
  privateKey: text('private_key').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  alg: text('alg'),
  crv: text('crv'),
});

/** An MCP client (an AI chat app), most often created by dynamic client registration. */
export const oauthClient = pgTable(
  'oauth_client',
  {
    id: text('id').primaryKey(),
    clientId: text('client_id').notNull().unique(),
    clientSecret: text('client_secret'),
    clientDiscoveryId: text('client_discovery_id'),
    disabled: boolean('disabled').default(false),
    skipConsent: boolean('skip_consent'),
    enableEndSession: boolean('enable_end_session'),
    subjectType: text('subject_type'),
    scopes: textArray('scopes'),
    clientCredentialsScopes: textArray('client_credentials_scopes').default(sql`'{}'::text[]`),
    userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }),
    updatedAt: timestamp('updated_at', { withTimezone: true }),
    name: text('name'),
    uri: text('uri'),
    icon: text('icon'),
    contacts: textArray('contacts'),
    tos: text('tos'),
    policy: text('policy'),
    softwareId: text('software_id'),
    softwareVersion: text('software_version'),
    softwareStatement: text('software_statement'),
    redirectUris: textArray('redirect_uris').notNull(),
    postLogoutRedirectUris: textArray('post_logout_redirect_uris'),
    backchannelLogoutUri: text('backchannel_logout_uri'),
    backchannelLogoutSessionRequired: boolean('backchannel_logout_session_required'),
    tokenEndpointAuthMethod: text('token_endpoint_auth_method'),
    applicationType: text('application_type'),
    jwks: text('jwks'),
    jwksUri: text('jwks_uri'),
    grantTypes: textArray('grant_types'),
    responseTypes: textArray('response_types'),
    requirePKCE: boolean('require_pkce'),
    dpopBoundAccessTokens: boolean('dpop_bound_access_tokens').default(false),
    referenceId: text('reference_id'),
    metadata: jsonb('metadata'),
  },
  (table) => [index('oauth_client_user_id_idx').on(table.userId)],
);

/** A protected resource tokens are issued for: the MCP endpoint (`<base URL>/mcp`). */
export const oauthResource = pgTable('oauth_resource', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull().unique(),
  name: text('name').notNull(),
  accessTokenTtl: integer('access_token_ttl'),
  refreshTokenTtl: integer('refresh_token_ttl'),
  signingAlgorithm: text('signing_algorithm'),
  signingKeyId: text('signing_key_id'),
  allowedScopes: textArray('allowed_scopes'),
  customClaims: jsonb('custom_claims'),
  dpopBoundAccessTokensRequired: boolean('dpop_bound_access_tokens_required').default(false),
  disabled: boolean('disabled').default(false),
  createdAt: timestamp('created_at', { withTimezone: true }),
  updatedAt: timestamp('updated_at', { withTimezone: true }),
  policyVersion: integer('policy_version').default(1),
  metadata: jsonb('metadata'),
});

export const oauthClientResource = pgTable(
  'oauth_client_resource',
  {
    id: text('id').primaryKey(),
    clientId: text('client_id')
      .notNull()
      .references(() => oauthClient.clientId, { onDelete: 'cascade' }),
    resourceId: text('resource_id')
      .notNull()
      .references(() => oauthResource.identifier, { onDelete: 'cascade' }),
    metadata: jsonb('metadata'),
    createdAt: timestamp('created_at', { withTimezone: true }),
  },
  (table) => [
    index('oauth_client_resource_client_id_idx').on(table.clientId),
    index('oauth_client_resource_resource_id_idx').on(table.resourceId),
    uniqueIndex('oauth_client_resource_client_resource_idx').on(table.clientId, table.resourceId),
  ],
);

export const oauthRefreshToken = pgTable(
  'oauth_refresh_token',
  {
    id: text('id').primaryKey(),
    token: text('token').notNull().unique(),
    clientId: text('client_id')
      .notNull()
      .references(() => oauthClient.clientId, { onDelete: 'cascade' }),
    sessionId: text('session_id').references(() => session.id, { onDelete: 'set null' }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    referenceId: text('reference_id'),
    authorizationCodeId: text('authorization_code_id'),
    resources: textArray('resources'),
    requestedUserInfoClaims: textArray('requested_user_info_claims'),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }),
    revoked: timestamp('revoked', { withTimezone: true }),
    rotatedAt: timestamp('rotated_at', { withTimezone: true }),
    rotationReplayResponse: text('rotation_replay_response'),
    rotationReplayExpiresAt: timestamp('rotation_replay_expires_at', { withTimezone: true }),
    authTime: timestamp('auth_time', { withTimezone: true }),
    confirmation: jsonb('confirmation'),
    scopes: textArray('scopes').notNull(),
  },
  (table) => [
    index('oauth_refresh_token_client_id_idx').on(table.clientId),
    index('oauth_refresh_token_session_id_idx').on(table.sessionId),
    index('oauth_refresh_token_user_id_idx').on(table.userId),
    index('oauth_refresh_token_authorization_code_id_idx').on(table.authorizationCodeId),
  ],
);

export const oauthAccessToken = pgTable(
  'oauth_access_token',
  {
    id: text('id').primaryKey(),
    token: text('token').unique(),
    clientId: text('client_id')
      .notNull()
      .references(() => oauthClient.clientId, { onDelete: 'cascade' }),
    sessionId: text('session_id').references(() => session.id, { onDelete: 'set null' }),
    userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }),
    referenceId: text('reference_id'),
    authorizationCodeId: text('authorization_code_id'),
    resources: textArray('resources'),
    requestedUserInfoClaims: textArray('requested_user_info_claims'),
    refreshId: text('refresh_id').references(() => oauthRefreshToken.id, { onDelete: 'cascade' }),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }),
    revoked: timestamp('revoked', { withTimezone: true }),
    confirmation: jsonb('confirmation'),
    scopes: textArray('scopes').notNull(),
  },
  (table) => [
    index('oauth_access_token_client_id_idx').on(table.clientId),
    index('oauth_access_token_session_id_idx').on(table.sessionId),
    index('oauth_access_token_user_id_idx').on(table.userId),
    index('oauth_access_token_authorization_code_id_idx').on(table.authorizationCodeId),
    index('oauth_access_token_refresh_id_idx').on(table.refreshId),
  ],
);

/** What a user allowed a client to do (the consent page). */
export const oauthConsent = pgTable(
  'oauth_consent',
  {
    id: text('id').primaryKey(),
    clientId: text('client_id')
      .notNull()
      .references(() => oauthClient.clientId, { onDelete: 'cascade' }),
    userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }),
    referenceId: text('reference_id'),
    resources: textArray('resources'),
    requestedUserInfoClaims: textArray('requested_user_info_claims'),
    scopes: textArray('scopes').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }),
    updatedAt: timestamp('updated_at', { withTimezone: true }),
  },
  (table) => [
    index('oauth_consent_client_id_idx').on(table.clientId),
    index('oauth_consent_user_id_idx').on(table.userId),
  ],
);

/** Client assertion JWT ids already used (replay protection for `private_key_jwt`). */
export const oauthClientAssertion = pgTable('oauth_client_assertion', {
  id: text('id').primaryKey(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
});

/** The tables above, keyed by Better Auth model name, for its Drizzle adapter. */
export const mcpAuthSchema = {
  jwks,
  oauthClient,
  oauthResource,
  oauthClientResource,
  oauthRefreshToken,
  oauthAccessToken,
  oauthConsent,
  oauthClientAssertion,
};

// --- Learner progress ---------------------------------------------------------

export const learner = pgTable('learner', {
  /** The signed-in user (or the single local user in `LESSONFOLK_AUTH=none`). */
  userId: text('user_id')
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  profile: jsonb('profile').$type<LearnerProfile>().notNull().default({}),
  /** Recommended course ids, in order. */
  path: text('path').array(),
  pathReason: text('path_reason'),
  pathUpdatedAt: timestamp('path_updated_at', { withTimezone: true }),
  /** Lesson id (`<course-id>/<lesson file name>`) the learner is working on. */
  currentLessonId: text('current_lesson_id'),
  ...timestamps,
});

export const lessonProgress = pgTable(
  'lesson_progress',
  {
    userId: text('user_id')
      .notNull()
      .references(() => learner.userId, { onDelete: 'cascade' }),
    lessonId: text('lesson_id').notNull(),
    status: text('status').$type<LessonStatus>().notNull(),
    startedAt: timestamp('started_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    /** 0–1, the tutor's estimate from the checks. */
    score: real('score'),
    notes: text('notes'),
    ...timestamps,
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.lessonId] }),
    check('lesson_progress_status_check', sql`${table.status} in ('in_progress', 'done', 'skipped')`),
    check('lesson_progress_score_check', sql`${table.score} is null or (${table.score} >= 0 and ${table.score} <= 1)`),
  ],
);

/** Append-only: rows are inserted, never updated or deleted (except with their learner). */
export const progressEvent = pgTable(
  'progress_event',
  {
    id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
    userId: text('user_id')
      .notNull()
      .references(() => learner.userId, { onDelete: 'cascade' }),
    /** What happened, e.g. `lesson.started`, `lesson.completed`, `path.updated`. */
    action: text('action').notNull(),
    payload: jsonb('payload').$type<Record<string, unknown>>().notNull().default({}),
    /** Which client made the change (e.g. `claude-code`, `codex`, `dashboard`). */
    client: text('client'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index('progress_event_user_created_idx').on(table.userId, table.createdAt)],
);

export type User = typeof user.$inferSelect;
export type NewUser = typeof user.$inferInsert;
export type Learner = typeof learner.$inferSelect;
export type NewLearner = typeof learner.$inferInsert;
export type LessonProgress = typeof lessonProgress.$inferSelect;
export type NewLessonProgress = typeof lessonProgress.$inferInsert;
export type ProgressEvent = typeof progressEvent.$inferSelect;
export type NewProgressEvent = typeof progressEvent.$inferInsert;
